# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Node.js_CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t harishgarg2508/nodejs-ec2-cicd:latest .

      - name: Push image to Docker Hub
        run: docker push harishgarg2508/nodejs-ec2-cicd:latest
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull harishgarg2508/nodejs-ec2-cicd:latest
      - name: Delete old container
        run: docker rm -f nodejs-ec2-cicd-container
      - name: Run docker container
        run: docker run -d -p 5000:5000 --name nodejs-ec2-cicd-container harishgarg2508/nodejs-ec2-cicd